// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxOBW6BFhc39GyiVjV7TYxAkgCNy-PkKQ',
    appId: '1:1011760339228:web:844150fc25a77857b3c2d9',
    messagingSenderId: '1011760339228',
    projectId: 'logitrack-app-ahmad',
    authDomain: 'logitrack-app-ahmad.firebaseapp.com',
    storageBucket: 'logitrack-app-ahmad.firebasestorage.app',
    measurementId: 'G-ERY89YDJ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmDqeU8aPok0iqeHCTecVXAPkVUYZRP7g',
    appId: '1:1011760339228:android:fcee77bbe7556231b3c2d9',
    messagingSenderId: '1011760339228',
    projectId: 'logitrack-app-ahmad',
    storageBucket: 'logitrack-app-ahmad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYCManM-Jwi6q4Ga0Q7i8kWFcn7kDBCk',
    appId: '1:1011760339228:ios:23525e7f18c4629ab3c2d9',
    messagingSenderId: '1011760339228',
    projectId: 'logitrack-app-ahmad',
    storageBucket: 'logitrack-app-ahmad.firebasestorage.app',
    iosBundleId: 'com.example.logitrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqYCManM-Jwi6q4Ga0Q7i8kWFcn7kDBCk',
    appId: '1:1011760339228:ios:23525e7f18c4629ab3c2d9',
    messagingSenderId: '1011760339228',
    projectId: 'logitrack-app-ahmad',
    storageBucket: 'logitrack-app-ahmad.firebasestorage.app',
    iosBundleId: 'com.example.logitrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxOBW6BFhc39GyiVjV7TYxAkgCNy-PkKQ',
    appId: '1:1011760339228:web:10dbde630d4cd85eb3c2d9',
    messagingSenderId: '1011760339228',
    projectId: 'logitrack-app-ahmad',
    authDomain: 'logitrack-app-ahmad.firebaseapp.com',
    storageBucket: 'logitrack-app-ahmad.firebasestorage.app',
    measurementId: 'G-RWBR2E2W53',
  );
}
